name: Firebase Deployment

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.0.0'  # Use the Node.js version compatible with your Next.js app

    - name: Install dependencies
      run: |
        npm install

    - name: Build Next.js app
      run: |
        npm run build

    - name: Install Firebase CLI
      run: |
        npm install -g firebase-tools

    - name: Deploy to Firebase
      run: |
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
